### ISSUE TITLE
Identified motifs missing in nanomotif assignment table

### ISSUE THREAD

**Issue by KerrinSteensen** [MicrobialDarkMatter/nanomotif#60]
Hi, 

I have a question regarding the nanomotif output. We used a bacterial isolate as input.
Some of the motifs in the motifs.tsv file don't show up in the nanomotif_assignment_table. I was wondering whether there is a specific reason why they are not in there (e.g. a filtering step?)

I am attaching the nanomotif output files of an example genome.
For example, the motif "CTCGAG" is in the motif.tsv file, but not in the assignment table.

Thank you for your help!

[motifs.txt](https://github.com/user-attachments/files/16194936/motifs.txt)
[mtase_assignment_table.txt](https://github.com/user-attachments/files/16194937/mtase_assignment_table.txt)
[nanomotif_assignment_table.txt](https://github.com/user-attachments/files/16194938/nanomotif_assignment_table.txt)

**Comment by JSBoejer** [comment]
The reason for this is that you probably have used the bin_motifs.tsv file (as you should) when executing the nanomotif 'MTase-linker run' command creating the nanomotif_assignment_table. You should see an agreement between the bin_motifs.tsv and the nanomotif_assignment_table.

The key difference between motifs.tsv and bin_motifs.tsv lies in the series of post-processing steps applied to improve the final motifs. For more details on these post-processing steps, refer to supplementary note 1 of our preprint: https://www.biorxiv.org/content/10.1101/2024.04.29.591623v1

Also, only motifs with a degree of methylation above 50% in bin_motifs.tsv will be included the assignment process. Thus, CTCGAG will not be included since the degree of methylation for this motif is below 50%.

**Comment by KerrinSteensen** [comment]
That makes total sense. Thanks for the quick response!

**Comment by KerrinSteensen** [comment]
Hi again, 

We looked at the data in more depth, and we were wondering if there is a specific reason why the threshold of the "degree of methylation" is set to 50%. We are working with isolates, and we wonder if a methylation of ~30-40 % might also be interesting in this case. Is there a known technical reason why this should not be done?

Otherwise, do you think it might be possible to add an -isolate or -methylation_perc option? 

Thank you!

**Comment by SorenHeidelbach** [comment]
Hi again
I want to clarify that the degree of methylation, that I referred to, was the proportion of motif occurrences in the bin, which are methylated. From literature (Beaulaurier 2019 provided a good review), we know that if a methylation motif is targeted by an MTase, typically >95% of motif occurrences are methylated. This is the reason why we choose this threshold of 50%.
In your case with isolates, looking at methylation degree for a fixed position and motif at the read level is definitely interesting, especially for similar strains. To clarify, for a specific motif on a fixed position in the genome, the degree of methylation of the reads at this position might indicate epigenetic regulation leading to different phenotypes. For instance, in S.enterica, we will observe different serotypes depending on the methylation status of the GATC motifs in the gtr promotor. Nanomotif does not give you the methylation degree of a specific motif on a specific position explicitly yet, however we are working on providing this as an output. Meanwhile you should be able to combine the information from methylation pileup file and bin-motifs file to get the proportion of methylated reads (fraction modified column) for a given motif at a given position (See attached figure)
I hope this answer was helpful.

Sorry for the long answer time
